//
// Created by matthew on 11/07/2020.
//

#ifndef DATABASE_MANAGER_REQUESTTYPE_H
#define DATABASE_MANAGER_REQUESTTYPE_H

enum class RequestType {
    DRAWING_SEARCH_QUERY,
    DRAWING_ADD,
    SOURCE_PRODUCT_TABLE,
    SOURCE_APERTURE_TABLE,
    SOURCE_APERTURE_SHAPE_TABLE,
    SOURCE_MATERIAL_TABLE,
    SOURCE_SIDE_IRON_TABLE,
    SOURCE_MACHINE_TABLE,
    SOURCE_MACHINE_DECK_TABLE
};

#endif //DATABASE_MANAGER_REQUESTTYPE_H
