//
// Created by matthew on 11/07/2020.
//

#ifndef DATABASE_MANAGER_REQUESTTYPE_H
#define DATABASE_MANAGER_REQUESTTYPE_H

enum class RequestType {
    REPEAT_TOKEN_REQUEST,
    USER_EMAIL_REQUEST,
    DRAWING_SEARCH_QUERY,
    DRAWING_INSERT,
    SOURCE_PRODUCT_TABLE,
    SOURCE_APERTURE_TABLE,
    SOURCE_APERTURE_SHAPE_TABLE,
    SOURCE_MATERIAL_TABLE,
    SOURCE_SIDE_IRON_TABLE,
    SOURCE_SIDE_IRON_PRICES_TABLE,
    SOURCE_MACHINE_TABLE,
    SOURCE_MACHINE_DECK_TABLE,
    SOURCE_EXTRA_PRICES_TABLE,
    DRAWING_DETAILS,
    ADD_NEW_COMPONENT,
    GET_NEXT_DRAWING_NUMBER,
    CREATE_DATABASE_BACKUP
};

enum class MaterialPricingType {
    RUNNING_M,
    SQUARE_M,
    SHEET,

    TOTAL
};

enum class ExtraPriceType {
    SIDE_IRON_NUTS,
    SIDE_IRON_SCREWS,
    TACKYBACK_GLUE,
    LABOUR
};
#endif //DATABASE_MANAGER_REQUESTTYPE_H
